# Generated by Django 3.0.8 on 2020-07-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowie', '0002_auto_20200714_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
